from django.urls import path

from .views import (
    CustomerChoicesAPI,
    CustomerListCreateAPI,
    CustomerDetailAPI,
    QuoteListCreateAPI,
    QuoteDetailAPI,
    QuoteSendAPI,
    QuoteChoicesAPI,
    InvoiceListCreateAPI,
    InvoiceDetailAPI,
    InvoicePostAPI,
    InvoiceZatcaSubmitAPI,
    InvoiceZatcaVerifyAPI,
    InvoiceChoicesAPI,
    CustomerPaymentChoicesAPI,
    CustomerPaymentListCreateAPI,
    CustomerPaymentDetailAPI,
    CustomerOutstandingInvoicesAPI,
    CustomerRefundListCreateAPI,
    CustomerRefundDetailAPI,
    CustomerOutstandingCreditNotesAPI,
    CustomerCreditNoteChoicesAPI,
    CustomerCreditNoteListCreateAPI,
    CustomerCreditNoteDetailAPI,
    CustomerCreditNotePostAPI,
    CreditNoteZatcaSubmitAPI,
    CreditNoteZatcaVerifyAPI,
)

app_name = "sales"

urlpatterns = [
    path("customers/choices/", CustomerChoicesAPI.as_view(), name="customer-choices"),
    path("customers/", CustomerListCreateAPI.as_view(), name="customer-list-create"),
    path("customers/<uuid:pk>/", CustomerDetailAPI.as_view(), name="customer-detail"),
    path("quotes/choices/", QuoteChoicesAPI.as_view(), name="quote-choices"),
    path("quotes/", QuoteListCreateAPI.as_view(), name="quote-list-create"),
    path("quotes/<uuid:pk>/", QuoteDetailAPI.as_view(), name="quote-detail"),
    path("quotes/<uuid:pk>/send/", QuoteSendAPI.as_view(), name="quote-send"),
    path("invoices/choices/", InvoiceChoicesAPI.as_view(), name="invoice-choices"),
    path("invoices/", InvoiceListCreateAPI.as_view(), name="invoice-list-create"),
    path("invoices/<uuid:pk>/", InvoiceDetailAPI.as_view(), name="invoice-detail"),
    path("invoices/<uuid:pk>/post/", InvoicePostAPI.as_view(), name="invoice-post"),
    path("invoices/<uuid:pk>/zatca/submit/", InvoiceZatcaSubmitAPI.as_view(), name="invoice-zatca-submit"),
    path("invoices/<uuid:pk>/zatca/verify/", InvoiceZatcaVerifyAPI.as_view(), name="invoice-zatca-verify"),
    path("customer-payments/choices/", CustomerPaymentChoicesAPI.as_view(), name="customer-payment-choices"),
    path("customer-payments/", CustomerPaymentListCreateAPI.as_view(), name="customer-payment-list-create"),
    path("customer-payments/<uuid:pk>/", CustomerPaymentDetailAPI.as_view(), name="customer-payment-detail"),
    path("customer-payments/outstanding-invoices/", CustomerOutstandingInvoicesAPI.as_view(), name="customer-outstanding-invoices"),
    path("customer-refunds/", CustomerRefundListCreateAPI.as_view(), name="customer-refund-list-create"),
    path("customer-refunds/<uuid:pk>/", CustomerRefundDetailAPI.as_view(), name="customer-refund-detail"),
    path("customer-refunds/outstanding-credit-notes/", CustomerOutstandingCreditNotesAPI.as_view(), name="customer-outstanding-credit-notes"),
    path("credit-notes/choices/", CustomerCreditNoteChoicesAPI.as_view(), name="customer-credit-note-choices"),
    path("credit-notes/", CustomerCreditNoteListCreateAPI.as_view(), name="customer-credit-note-list-create"),
    path("credit-notes/<uuid:pk>/", CustomerCreditNoteDetailAPI.as_view(), name="customer-credit-note-detail"),
    path("credit-notes/<uuid:pk>/post/", CustomerCreditNotePostAPI.as_view(), name="customer-credit-note-post"),
    path("credit-notes/<uuid:pk>/zatca/submit/", CreditNoteZatcaSubmitAPI.as_view(), name="credit-note-zatca-submit"),
    path("credit-notes/<uuid:pk>/zatca/verify/", CreditNoteZatcaVerifyAPI.as_view(), name="credit-note-zatca-verify"),
]

