"""
Django settings for zatca_accounting_software project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is required.")

# SECURITY WARNING: don't run with debug turned on in production.
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]

# VAT rounding strategy: "line" (default) or "invoice"
VAT_ROUNDING_STRATEGY = os.getenv("VAT_ROUNDING_STRATEGY", "line").strip().lower()

# When True, get_system_account() never falls back to Account.code.
# Default: strict in production (DEBUG=False), relaxed in development unless explicitly forced.
_strict_env = (os.getenv("ACCOUNTING_STRICT_SYSTEM_ACCOUNTS", "") or "").strip().lower()
if _strict_env in {"1", "true", "yes", "on"}:
    ACCOUNTING_STRICT_SYSTEM_ACCOUNTS = True
elif _strict_env in {"0", "false", "no", "off"}:
    ACCOUNTING_STRICT_SYSTEM_ACCOUNTS = False
else:
    ACCOUNTING_STRICT_SYSTEM_ACCOUNTS = not DEBUG


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'main',
    'user',
    'accounting.apps.AccountingConfig',
    'products',
    'purchases',
    'sales',
]

AUTH_USER_MODEL = 'user.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'zatca_accounting_software.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'zatca_accounting_software.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static & media files
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media (user-uploaded) files — served by nginx via alias (see nginx config).
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Max upload size (e.g. for user photos) - 10 MB
MAX_UPLOAD_SIZE = 10 * 1024 * 1024

# ── Email (SMTP) ──────────────────────────────────────────────────────────────
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'ZATCA Accounting <noreply@zatca.com>')

# ── Backend URL (for internal use) ────────────────────────────────────────────
BACKEND_URL = os.getenv('BACKEND_URL', 'https://zatca-backend.loopive.com')

# ── Frontend URL (used in invitation emails so users land on the React app) ───
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://zatca-accounting-software.loopive.com')

# ── CORS ──────────────────────────────────────────────────────────────────────
_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "idempotency-key",
]


def _env_bool(name: str, default: bool = False) -> bool:
    v = (os.getenv(name, "") or "").strip().lower()
    if v in {"1", "true", "yes", "on"}:
        return True
    if v in {"0", "false", "no", "off"}:
        return False
    return default


# When True, new invoice/credit-note posting is blocked if the last verify_zatca_hash_chain run failed.
# Default: on in production so a broken chain cannot accumulate more documents unnoticed.
ZATCA_BLOCK_POST_ON_CHAIN_FAILURE = _env_bool(
    "ZATCA_BLOCK_POST_ON_CHAIN_FAILURE",
    default=not DEBUG,
)

# Optional TLV tags 7–9 (ECDSA) in QR — enable only when your certification profile requires them.
ZATCA_QR_INCLUDE_ECDSA = _env_bool("ZATCA_QR_INCLUDE_ECDSA", default=False)

# When False, invoice/credit-note posting builds unsigned XML artifacts but does NOT require a
# ZATCA certificate.  Signing + submission to Fatoora happens later via the "Report to Fatoora"
# button (a dedicated API call).  Set to True only after your ZATCA certificate is onboarded.
ZATCA_SIGNING_ENABLED = _env_bool("ZATCA_SIGNING_ENABLED", default=False)

# ZATCA API simulation (no HTTP to authority). Unset env → True when DEBUG=True, False when DEBUG=False.
_zat_sim = (os.getenv("ZATCA_SIMULATION_MODE", "") or "").strip().lower()
if _zat_sim in {"1", "true", "yes", "on"}:
    ZATCA_SIMULATION_MODE = True
elif _zat_sim in {"0", "false", "no", "off"}:
    ZATCA_SIMULATION_MODE = False
else:
    ZATCA_SIMULATION_MODE = DEBUG

# When True (default in production), JournalEntry.post() must run inside journal_post_gate / AccountingEngine.
_je_gate = (os.getenv("ENFORCE_JOURNAL_ENTRY_POST_GATE", "") or "").strip().lower()
if _je_gate in {"1", "true", "yes", "on"}:
    ENFORCE_JOURNAL_ENTRY_POST_GATE = True
elif _je_gate in {"0", "false", "no", "off"}:
    ENFORCE_JOURNAL_ENTRY_POST_GATE = False
else:
    ENFORCE_JOURNAL_ENTRY_POST_GATE = not DEBUG

# Persisted ZATCA evidence on successful HTTP responses must pass is_complete() when strict.
_zat_ev = (os.getenv("ZATCA_STRICT_EVIDENCE_COMPLETENESS", "") or "").strip().lower()
if _zat_ev in {"1", "true", "yes", "on"}:
    ZATCA_STRICT_EVIDENCE_COMPLETENESS = True
elif _zat_ev in {"0", "false", "no", "off"}:
    ZATCA_STRICT_EVIDENCE_COMPLETENESS = False
else:
    ZATCA_STRICT_EVIDENCE_COMPLETENESS = not DEBUG
